# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycurl < Formula
  desc "A Lazygit-style TUI HTTP client for API testing"
  homepage "https://github.com/kbrdn1/LazyCurl"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kbrdn1/LazyCurl/releases/download/v1.2.0/LazyCurl_1.2.0_darwin_amd64.tar.gz"
      sha256 "9c4a95e112568c9b498f7be37d9a27b50acf39cdf78c371f658f236ea99fa2ca"

      def install
        bin.install "lazycurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kbrdn1/LazyCurl/releases/download/v1.2.0/LazyCurl_1.2.0_darwin_arm64.tar.gz"
      sha256 "c4bf9f85f8a8603ffa2ae3b3193d2aa7428732754a73e75e3a425d78d79a1a1b"

      def install
        bin.install "lazycurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kbrdn1/LazyCurl/releases/download/v1.2.0/LazyCurl_1.2.0_linux_amd64.tar.gz"
      sha256 "0c2ad3c77dd4c347a90ed0aa694a00579a63b933c19c37d4514d7e680d6fd6f0"
      def install
        bin.install "lazycurl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kbrdn1/LazyCurl/releases/download/v1.2.0/LazyCurl_1.2.0_linux_arm64.tar.gz"
      sha256 "a32c8515145f517e49a062d039d101c9bfed08695de50fd408c11b820f52543d"
      def install
        bin.install "lazycurl"
      end
    end
  end

  test do
    system "#{bin}/lazycurl", "--version"
  end
end
