# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycurl < Formula
  desc "A Lazygit-style TUI HTTP client for API testing"
  homepage "https://github.com/kbrdn1/LazyCurl"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kbrdn1/LazyCurl/releases/download/v1.0.0/LazyCurl_1.0.0_darwin_amd64.tar.gz"
      sha256 "4ec12feb5b7e5a42f2855bd92decb5ae8dc9aa8b0a2a429585930755ef0546a1"

      def install
        bin.install "lazycurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kbrdn1/LazyCurl/releases/download/v1.0.0/LazyCurl_1.0.0_darwin_arm64.tar.gz"
      sha256 "795c72a919923c313b37c8c55500ba5b688a08124d79c25e6ce9dc8ecd1a30d4"

      def install
        bin.install "lazycurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kbrdn1/LazyCurl/releases/download/v1.0.0/LazyCurl_1.0.0_linux_amd64.tar.gz"
      sha256 "dde8df96c336d489393324803da22b55061aefafaa34008e62a43ddd4756d608"
      def install
        bin.install "lazycurl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kbrdn1/LazyCurl/releases/download/v1.0.0/LazyCurl_1.0.0_linux_arm64.tar.gz"
      sha256 "377da44ae3000e2688991f85cf4c8b1a6d6684fc8270d3188dfb5c58d9c802c7"
      def install
        bin.install "lazycurl"
      end
    end
  end

  test do
    system "#{bin}/lazycurl", "--version"
  end
end
